// <auto-generated />
using System;
using KPI_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KPI_Project.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250511171450_changeToDateTime")]
    partial class changeToDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KPI_Project.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Isbn");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Books__3214EC07488796A4");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Alice Munro",
                            Description = "A mysterious novel about forgotten histories.",
                            Isbn = "978-1-4028-9462-6",
                            Price = 150.00m,
                            PublishedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lost Pages"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Brian Kernighan",
                            Description = "An in-depth guide to coding practices in stealthy environments.",
                            Isbn = "978-0-13-110362-7",
                            Price = 175.00m,
                            PublishedDate = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Code in the Shadows"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Cathy O'Neil",
                            Description = "A thoughtful exploration of how data shapes our world.",
                            Isbn = "978-0-8129-9823-6",
                            Price = 150.00m,
                            PublishedDate = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data and Destiny"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Don Knuth",
                            Description = "An expert look at algorithms under time pressure.",
                            Isbn = "978-0-201-03801-2",
                            Price = 125.00m,
                            PublishedDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight Algorithms"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Elena Garcia",
                            Description = "Fictional journey into the quantum realm.",
                            Isbn = "978-1-56619-909-4",
                            Price = 100.00m,
                            PublishedDate = new DateTime(2019, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Quantum Leaves"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
