// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace KPI_Project.Models;

public partial class AppDBContext : DbContext
{
    public AppDBContext(DbContextOptions<AppDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Book> Books { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Books__3214EC07488796A4");

            entity.Property(e => e.Author)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Isbn)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Isbn");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);


        //Seed Data
        modelBuilder.Entity<Book>()
            .HasData(new
            {
                Id = 1,
                Title = "The Lost Pages",
                Author = "Alice Munro",
                Isbn = "978-1-4028-9462-6",
                Price = 150.00m,
                PublishedDate = DateTime.Parse("2022-01-15"),
                Description = "A mysterious novel about forgotten histories."
            });

        modelBuilder.Entity<Book>()
           .HasData(new
           {
               Id = 2,
               Title = "Code in the Shadows",
               Author = "Brian Kernighan",
               Isbn = "978-0-13-110362-7",
               Price = 175.00m,
               PublishedDate = DateTime.Parse("2021-07-30"),
               Description = "An in-depth guide to coding practices in stealthy environments."
           });

        modelBuilder.Entity<Book>()
           .HasData(new
           {
               Id = 3,
               Title = "Data and Destiny",
               Author = "Cathy O'Neil",
               Isbn = "978-0-8129-9823-6",
               Price = 150.00m,
               PublishedDate = DateTime.Parse("2020-03-10"),
               Description = "A thoughtful exploration of how data shapes our world."
           });

        modelBuilder.Entity<Book>()
           .HasData(new
           {
               Id = 4,
               Title = "Midnight Algorithms",
               Author = "Don Knuth",
               Isbn = "978-0-201-03801-2",
               Price = 125.00m,
               PublishedDate = DateTime.Parse("2023-11-05"),
               Description = "An expert look at algorithms under time pressure."
           });

        modelBuilder.Entity<Book>()
           .HasData(new
           {
               Id = 5,
               Title = "Quantum Leaves",
               Author = "Elena Garcia",
               Isbn = "978-1-56619-909-4",
               Price = 100.00m,
               PublishedDate = DateTime.Parse("2019-06-25"),
               Description = "Fictional journey into the quantum realm."
           });
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}